### ISSUE TITLE
Double loop takes long

### ISSUE THREAD

**Issue by bakeromso** [plumped/camt_converter_ISO20022_for_camt#5]
First of all, nice work!

Secondly, I would like to address the issue of having a double loop at the following line in [xml_parsing.py](https://github.com/plumped/camt_converter_ISO20022_for_camt/blob/9087a7dc8780e529d3276b555a6c38b345e26253/src/xmlparser.py#L75). I debugged this Python file, and this double loop causes the program for me to take quite long to run. 

I can't find a solution right away, but the double loop causes the running time to grow quadratically. For N tags, the double loop takes N*N iterations.

**Comment by plumped** [comment]
Hi @bakeromso 

I already recognized it and find also another problem with the output. working on it and will release a fixed more performant solution.
