### ISSUE TITLE
Uncaught exceptions and code style

### ISSUE THREAD

**Issue by bakeromso** [plumped/camt_converter_ISO20022_for_camt#6]
The variable `key` is used [here](https://github.com/plumped/camt_converter_ISO20022_for_camt/blob/9087a7dc8780e529d3276b555a6c38b345e26253/src/xmlparser.py#L81), being declared [here](https://github.com/plumped/camt_converter_ISO20022_for_camt/blob/9087a7dc8780e529d3276b555a6c38b345e26253/src/xmlparser.py#L57). However, this declaration happens in an if-statement. When it evaluates to `False`, and so the if-statement is not executed, the value `key` is left undeclared. However, it is used [here](https://github.com/plumped/camt_converter_ISO20022_for_camt/blob/9087a7dc8780e529d3276b555a6c38b345e26253/src/xmlparser.py#L81) `ibanList[key].append(a)`

Also, [the regex search](https://github.com/plumped/camt_converter_ISO20022_for_camt/blob/9087a7dc8780e529d3276b555a6c38b345e26253/src/xmlparser.py#L55) failed for me because my zip file does not contain an IBAN. Since you're enforcing this, maybe you should catch this exception or test whether re.search() does not return `None`. 

Are you aware of the standard module [Pathlib](https://docs.python.org/3/library/pathlib.html)? It made my experience much better working with file paths, being compatible with Linux and Windows style file paths. Also, it has built-in methods for [finding the extension of a file](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffix).

I don't mean to be rude by giving unsolicited advice, I just mean to inform you of things I was unaware of earlier as well.

**Comment by plumped** [comment]
@bakeromso 
> Also, [the regex search](https://github.com/plumped/camt_converter_ISO20022_for_camt/blob/9087a7dc8780e529d3276b555a6c38b345e26253/src/xmlparser.py#L55) failed for me because my zip file does not contain an IBAN. Since you're enforcing this, maybe you should catch this exception or test whether re.search() does not return None.

Do you have the standard sepa camt? And is your camt.xml header filled with the following tree? Because in that case i could catch the IBAN there, which makes even more sense anyway.

<Acct>
    <Id>
	    <IBAN>XY123456789987654321</IBAN> **<----------- THIS HERE**
    </Id>
    <Ownr>
	    <Nm>Your Name</Nm>
	    <PstlAdr>
		    <StrtNm>Bla</StrtNm>
		    <BldgNb>10</BldgNb>
		    <PstCd>12345</PstCd>
		    <TwnNm>City</TwnNm>
		    <Ctry>CH</Ctry>
	    </PstlAdr>
    </Ownr>
    <Svcr>
	    <FinInstnId>
		    <BICFI>BankClearing</BICFI>
		    <Othr>
			    <Id>XYZ</Id>
			    <Issr>VAT-ID</Issr>
		    </Othr>
	    </FinInstnId>
    </Svcr>
</Acct>

**Comment by plumped** [comment]
fixed in latest release:
Destination IBAN number is no longer taken from the filename, but is now taken directly in the designated field in the xml
